name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  STRAPI_URL: https://tikweb-prod-app-cms.azurewebsites.net

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Read node version from `.nvmrc` file
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      # Install node
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvmrc.outputs.node_version }}

      # Install dependencies
      - run: npm ci

      # Run checks
      - run: npm run lint
      - run: npm run type-check
      - run: npm test
      - run: npm run build
